<?php

namespace SoftUniBlogBundle\Repository;

/**
 * AccommodationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccommodationRepository extends \Doctrine\ORM\EntityRepository
{
}
